# Generated by Django 2.1.3 on 2020-09-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('host', models.GenericIPAddressField(verbose_name='主机地址')),
                ('port', models.IntegerField(default=3306, verbose_name='主机端口')),
                ('pro', models.CharField(max_length=64, verbose_name='省份')),
                ('city', models.CharField(max_length=512, verbose_name='地市')),
                ('isp', models.CharField(max_length=32, verbose_name='运营商')),
                ('proxy', models.CharField(max_length=128, verbose_name='代理商')),
                ('notes', models.TextField(null=True, verbose_name='备注')),
            ],
        ),
    ]
