# Generated by Django 2.1.3 on 2020-09-18 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=128, verbose_name='厂家')),
                ('os', models.CharField(max_length=128, verbose_name='操作系统')),
                ('sn', models.CharField(max_length=128, verbose_name='序列号')),
                ('mem', models.CharField(max_length=128, verbose_name='内存')),
                ('cpu', models.CharField(max_length=128, verbose_name='CPU型号')),
                ('hostname', models.CharField(max_length=128, verbose_name='主机名')),
            ],
        ),
        migrations.AlterField(
            model_name='table',
            name='host',
            field=models.GenericIPAddressField(unique=True, verbose_name='主机地址'),
        ),
        migrations.AddField(
            model_name='info',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Table', to_field='host', verbose_name='主机IP'),
        ),
    ]
